"""Q1：在快照树的 lib_heavy_tests.py 上逐条跑 heavy_tests_in_command_text。用法：python3 q1_probe.py [快照目录]"""
import importlib.util, os, sys
S = sys.argv[1] if len(sys.argv) > 1 else "/tmp/claude-1000/three-way-attack/verification-split-r1/snap"
spec = importlib.util.spec_from_file_location("lib_heavy_tests", os.path.join(S, ".claude/hooks/lib_heavy_tests.py"))
lib = importlib.util.module_from_spec(spec); spec.loader.exec_module(lib)
R, C, H, CORE = S, S + "/crates/singlefs-checker", S + "/crates/singlefs-harness", S + "/crates/singlefs-core"
cases = [
 ("01 -p", "cargo test -p singlefs-checker", R),
 ("02 --package=", "cargo test --package=singlefs-checker", R),
 ("03 -psinglefs-checker", "cargo test -psinglefs-checker", R),
 ("04 cwd in package", "cargo test", C),
 ("05 cwd in package/tests", "cargo test", C + "/tests"),
 ("06 --manifest-path", "cargo test --manifest-path crates/singlefs-checker/Cargo.toml", R),
 ("07 --test name", "cargo test -p singlefs-checker --test first_transaction_step_seven_layer0", R),
 ("08 --tests", "cargo test -p singlefs-checker --tests", R),
 ("09 --all-targets", "cargo test -p singlefs-checker --all-targets", R),
 ("10 --test '*'", "cargo test -p singlefs-checker --test '*'", R),
 ("11 nextest", "cargo nextest run -p singlefs-checker", R),
 ("12 --config alias from root", "cargo --config 'alias.xt=\"test -p singlefs-checker\"' xt", R),
 ("13 two -p", "cargo test -p singlefs-core -p singlefs-checker", R),
 ("14 direct binary", "./target/release/deps/first_transaction_step_seven_layer0-0123456789abcdef", R),
 ("15 bash -c", "bash -c 'cargo test -p singlefs-checker'", R),
 ("16 env", "env RUST_BACKTRACE=1 cargo test -p singlefs-checker", R),
 ("17 nice", "nice -n 19 cargo test -p singlefs-checker", R),
 ("18 capped.sh", "bash research/scripts/capped.sh 16 cargo test -p singlefs-checker", R),
 ("19 memcap+capped", "bash research/scripts/run-with-memory-cap.sh 8G bash research/scripts/capped.sh 16 cargo test -p singlefs-checker --release", R),
 ("20 cd && cargo test", "cd crates/singlefs-checker && cargo test", R),
 ("21 --manifest-path= from /tmp", "cargo test --manifest-path=" + C + "/Cargo.toml", "/tmp"),
 ("22 -p glob", "cargo test -p 'singlefs-check*'", R),
 ("23 -p spec with version", "cargo test -p singlefs-checker@0.1.0", R),
 ("24 -p pkgid url", "cargo test -p 'path+file://" + C + "#singlefs-checker@0.1.0'", R),
 ("25 --config alias from harness dir", "cargo --config 'alias.xt=\"test -p singlefs-checker\"' xt", H),
 ("26 CARGO_ALIAS env from harness dir", "CARGO_ALIAS_XT='test -p singlefs-checker' cargo xt", H),
 ("27 --config alias from core dir", "cargo --config 'alias.xt=\"test -p singlefs-checker\"' xt", CORE),
 ("28 --workspace", "cargo test --workspace", R),
 ("29 --workspace --exclude core", "cargo test --workspace --exclude singlefs-core", R),
 ("30 cargo hack", "cargo hack test -p singlefs-checker", R),
 ("31 llvm-cov", "cargo llvm-cov -p singlefs-checker", R),
 ("32 miri", "cargo miri test -p singlefs-checker", R),
 ("33 mutants -p checker", "cargo mutants -p singlefs-checker", R),
 ("34 -C dir", "cargo -C crates/singlefs-checker test", R),
 ("35 nextest archive run from harness", "cargo nextest run --archive-file /tmp/a.tar.zst", H),
 ("36 debug binary", "target/debug/deps/record_checker_judges_absence_by_the_persisted_set-0123456789abcdef --nocapture", R),
 ("38 binary via find -exec", "find target -name 'second_transaction_step_zero_layer0-*' -type f -executable -exec {} \;", R),
 ("39 binary via $(ls)", "$(ls target/release/deps/second_transaction_step_zero_layer0-* | head -1)", R),
 ("40 binary copied renamed", "cp target/release/deps/second_transaction_step_zero_layer0-0123456789abcdef /tmp/t && /tmp/t", R),
 ("41 xargs", "ls target/release/deps/second_transaction_step_zero_layer0-* | xargs -I{} {}", R),
 ("43 cargo t", "cargo t -p singlefs-checker", R),
 ("44 --lib --tests in pkg dir", "cargo test --lib --tests", C),
 ("49 --doc", "cargo test -p singlefs-checker --doc", R),
 ("50 --lib", "cargo test -p singlefs-checker --lib", R),
 ("51 cd to var dir", "D=crates/singlefs-checker; cd $D && cargo test", R),
 ("53 subshell cd", "(cd crates/singlefs-checker && cargo test)", R),
 ("54 env -C", "env -C crates/singlefs-checker cargo test", R),
 ("57 eval", "eval 'cargo test -p singlefs-checker'", R),
 ("59 variable pkg", "P=singlefs-checker; cargo test -p $P", R),
 ("62 rustup run", "rustup run stable cargo test -p singlefs-checker", R),
 ("66 nextest from checker dir", "cargo nextest run", C),
 ("M1 mutants -p core (mutants.toml test_workspace=true)", "cargo mutants -p singlefs-core", R),
 ("M2 mutants --test-package checker", "cargo mutants -p singlefs-core --test-package singlefs-checker", R),
 ("X1 harness-only target from root", "cargo test --test crash_segments_per_device_and_torn_in_place_overwrites", R),
]
for label, text, cwd in cases:
    got = lib.heavy_tests_in_command_text(text, cwd, {})
    print(f"{label}\t{text.replace(S, '<snap>')}\tcwd={cwd.replace(S, '<snap>')}\t=> {[(g.kind, g.category) for g in got] or None}")
