"""bg-notify-r1 攻方腿的命令形态表（附录三 L1–L14 以外）。

每条：
  id        编号（X = 可能漏检、F = 可能误检、C = 对照）
  bg        交给 hook 的 tool_input.run_in_background
  hook      交给真 hook 判的命令原文（真实会写出来的样子，路径照真用法）
  exec      在模拟 harness 的外层 shell 里真跑的命令；与 hook 那一条只差把真活换成 work.sh，
            `&`、`wait`、nohup/setsid/disown、引号与 heredoc 的位置逐字相同；None = 不真跑（推的）
  why       这条为什么会被写出来 / 出处
占位：%%名字:秒数%% 展开成 `bash <本格目录>/work.sh 名字 秒数`（睡够秒数后写 done.名字）；%%DIR%% 展开成本格目录。
名字叫 gate 的是「要等的那件活」，叫 keepalive 的是缓存计时器。
"""
G = "/tmp/claude-1000/gate-triage-commit-0918"
GATE = "nice -n 19 bash .claude/scripts/gate.sh --staged"
KEEP = "bash research/scripts/cache-keepalive.sh"

SHAPES = [
    # ---- A1①：照新指令字面允许、却会脱钩的写法 ----
    dict(id="X01", bg=True,
         hook=f'{GATE} > {G}/gate-run.log 2>&1 & echo "started pid $!"',
         exec='%%gate:6%% > gate-run.log 2>&1 & echo "started pid $!"',
         why="事故那条（附录三 L1）照新指令字面删掉 nohup 与 disown 之后剩下的样子：& 不在末尾、没有 nohup/setsid/disown"),
    dict(id="X02", bg=True,
         hook=f'({GATE} > {G}/gate-run.log 2>&1 &)',
         exec='(%%gate:6%% > gate-run.log 2>&1 &)',
         why="子 shell 里放后台（双 fork 惯用法）；字面上 & 不在末尾（末尾是右括号）"),
    # ---- A2：hook 不记、却脱钩 ----
    dict(id="X03", bg=True,
         hook=f'{GATE} > {G}/gate-run.log 2>&1 & echo "gate.sh started as pid $!; I will wait for the notification"',
         exec='%%gate:6%% > gate-run.log 2>&1 & echo "gate.sh started as pid $!; I will wait for the notification"',
         why="& 后面只在 echo 的文字里出现 wait 这个词"),
    dict(id="X04", bg=True,
         hook=f'{GATE} > {G}/gate-run.log 2>&1 & {KEEP} & wait $!',
         exec='%%gate:6%% > gate-run.log 2>&1 & %%keepalive:2%% & wait $!',
         why="把长活和缓存计时器塞进同一条后台命令，wait $! 只等最后一个（计时器）"),
    dict(id="X05", bg=True,
         hook=f'{GATE} > {G}/gate-run.log 2>&1 & {KEEP} & wait -n',
         exec='%%gate:6%% > gate-run.log 2>&1 & %%keepalive:2%% & wait -n',
         why="wait -n：谁先完等谁，另一个脱钩"),
    dict(id="X06", bg=True,
         hook=f'({GATE} > {G}/gate-run.log 2>&1 &); wait',
         exec='(%%gate:6%% > gate-run.log 2>&1 &); wait',
         why="X02 加一个 wait：外层 shell 没有子进程可等，wait 当场返回"),
    dict(id="X07", bg=True,
         hook=f'pid=$({GATE} > {G}/gate-run.log 2>&1 & echo $!); echo "gate pid $pid"; wait "$pid"',
         exec='pid=$(%%gate:6%% > gate-run.log 2>&1 & echo $!); echo "gate pid $pid"; wait "$pid"',
         why="命令替换里起、外层 wait 那个 pid：它不是外层 shell 的子进程，wait 当场返回 127"),
    dict(id="X08", bg=True,
         hook=f'coproc GATE {{ {GATE} > {G}/gate-run.log 2>&1; }}',
         exec='coproc GATE { %%gate:6%% > gate-run.log 2>&1; }',
         why="coproc：不写 & 也是异步，外层 shell 不等它"),
    dict(id="X09", bg=True,
         hook=f"tmux new-session -d -s gate '{GATE} > {G}/gate-run.log 2>&1'",
         exec="tmux -L bgnr1-%%ID%% new-session -d -s gate -c %%DIR%% 'bash %%DIR%%/work.sh gate 6 > %%DIR%%/gate-run.log 2>&1'",
         why="tmux -d：模型常用的「放后台」写法之一"),
    dict(id="X10", bg=True,
         hook=f"screen -dmS gate bash -c '{GATE} > {G}/gate-run.log 2>&1'",
         exec="screen -dmS gate-bgnr1-%%ID%% bash -c 'bash %%DIR%%/work.sh gate 6 > %%DIR%%/gate-run.log 2>&1'",
         why="screen -dm：同上"),
    dict(id="X11", bg=True,
         hook=f"systemd-run --user --collect --unit gate-run {GATE}",
         exec=None,
         why="systemd-run 不带 --wait：起完单元就返回（没真跑，推的）"),
    dict(id="X12", bg=True,
         hook=f"nice -n 19 python3 - > {G}/rerun.log 2>&1 <<'EOF' &\nimport subprocess\np = subprocess.Popen(['bash', 'research/scripts/replay.sh'])\np.wait()\nEOF",
         exec="python3 - > rerun.log 2>&1 <<'EOF' &\nimport subprocess\np = subprocess.Popen(['bash', '%%DIR%%/work.sh', 'gate', '6'])\np.wait()\nEOF",
         why="heredoc 正文在外层 & 之后，正文里的 p.wait() 让 hook 以为有 wait"),
    dict(id="X13", bg=False,
         hook=f'{GATE} > {G}/gate-run.log 2>&1 &',
         exec='%%gate:6%% > gate-run.log 2>&1 &',
         why="同一条放后台的命令用前台 Bash 起（没带 run_in_background）：起完不会有任何完成通知"),
    # ---- A2：hook 记了、却不脱钩 ----
    dict(id="F01", bg=True,
         hook=f'nohup {GATE} > {G}/gate-run.log 2>&1',
         exec='nohup %%gate:4%% > gate-run.log 2>&1',
         why="习惯性加 nohup 但没加 &：nohup 不 fork，外层 shell 照样等它"),
    dict(id="F02", bg=True,
         hook=f'{GATE} > {G}/gate-run.log 2>&1 & pid=$!; while kill -0 "$pid" 2>/dev/null; do sleep 20; done; tail -3 {G}/gate-run.log',
         exec='%%gate:4%% > gate-run.log 2>&1 & pid=$!; while kill -0 "$pid" 2>/dev/null; do sleep 1; done; tail -3 gate-run.log',
         why="起了再按写死的 pid 轮询（command-safety.md「等一个进程结束，用它写死的 pid」那种等法）"),
    dict(id="F03", bg=True,
         hook=f'{GATE} > {G}/gate-run.log 2>&1 & tail --pid=$! -f {G}/gate-run.log > /dev/null',
         exec='%%gate:4%% > gate-run.log 2>&1 & tail --pid=$! -f gate-run.log > /dev/null',
         why="起了再用 tail --pid 跟着它"),
    dict(id="F04", bg=True,
         hook=f"nice -n 19 python3 - <<'EOF' > {G}/tally.txt\nimport json\nrows = [json.loads(line) for line in open('{G}/events.jsonl')]\nprint(sum(1 for row in rows if row['flags'] & 0x4))\nEOF",
         exec="python3 - <<'EOF' > tally.txt\nimport subprocess\nsubprocess.run(['bash', '%%DIR%%/work.sh', 'gate', '4'])\nprint(5 & 0x4)\nEOF",
         why="heredoc 里的 Python 按位与"),
    dict(id="F05", bg=True,
         hook="cat > /tmp/claude-1000/impl-probe/copy/crates/singlefs-harness/tests/probe.rs <<'EOF'\nfn digest(bytes: &[u8]) -> u64 { bytes.iter().map(|&b| b as u64).sum() }\n#[test]\nfn probe() { assert_eq!(digest(&[1, 2]), 3); }\nEOF\ncd /tmp/claude-1000/impl-probe/copy && nice -n 19 cargo test --release --test probe 2>&1 | tail -20",
         exec="cat > probe.rs <<'EOF'\nfn digest(bytes: &[u8]) -> u64 { bytes.iter().map(|&b| b as u64).sum() }\n#[test]\nfn probe() { assert_eq!(digest(&[1, 2]), 3); }\nEOF\n%%gate:4%% 2>&1 | tail -20",
         why="仓副本里 heredoc 写一段 Rust 再编译（Rust 的引用全是 &）"),
    dict(id="F06", bg=True,
         hook="nice -n 19 cargo test --release 2>&1 | sed -E 's/^test (.*) \\.\\.\\. FAILED$/!! &/' > /tmp/claude-1000/impl-probe/test.log",
         exec="%%gate:4%% 2>&1 | sed -E 's/^(.*)$/!! &/' > test.log",
         why="sed 替换串里的 &（整段匹配）"),
    dict(id="F07", bg=True,
         hook=f'setsid -w {GATE} > {G}/gate-run.log 2>&1',
         exec='setsid -w %%gate:4%% > gate-run.log 2>&1',
         why="setsid -w：另开会话但等它结束"),
    # ---- 对照：该记的记、该放的放 ----
    dict(id="C01", bg=True,
         hook=f'timeout 3600 {GATE} > {G}/gate-run.log 2>&1 &',
         exec='timeout 3600 %%gate:4%% > gate-run.log 2>&1 &',
         why="timeout … &"),
    dict(id="C02", bg=True,
         hook=f'timeout 3600 {GATE} > {G}/gate-run.log 2>&1',
         exec='timeout 3600 %%gate:4%% > gate-run.log 2>&1',
         why="timeout 不带 &"),
    dict(id="C03", bg=True,
         hook=f"printf '%s\\n' 54 55 57 | xargs -P 3 -I{{}} sh -c 'nice -n 19 bash .claude/gate.d/{{}}-*.sh > {G}/{{}}.log 2>&1'",
         exec="printf '%s\\n' a b c | xargs -P 3 -I{} sh -c 'bash %%DIR%%/work.sh {} 4 > %%DIR%%/{}.log 2>&1'",
         why="xargs -P 并行"),
    dict(id="C04", bg=True,
         hook=f"bash <<'EOF'\n{GATE} > {G}/gate-run.log 2>&1 &\nEOF",
         exec="bash <<'EOF'\n%%gate:4%% > gate-run.log 2>&1 &\nEOF",
         why="heredoc 喂给内层 shell、里面放后台"),
    dict(id="C05", bg=True,
         hook=f"bash <<'EOF'\n{GATE} > {G}/gate-run.log 2>&1 &\n{KEEP} &\nwait\nEOF",
         exec="bash <<'EOF'\n%%gate:4%% > gate-run.log 2>&1 &\n%%keepalive:2%% &\nwait\nEOF",
         why="heredoc 喂给内层 shell、并行加 wait"),
    dict(id="C06", bg=True,
         hook=f'exec {GATE} > {G}/gate-run.log 2>&1',
         exec='exec %%gate:4%% > gate-run.log 2>&1',
         why="exec 顶替外层 shell"),
    dict(id="C07", bg=True,
         hook=f'exec {GATE} > {G}/gate-run.log 2>&1 &',
         exec='exec %%gate:4%% > gate-run.log 2>&1 &',
         why="exec 加 &"),
    dict(id="C08", bg=True,
         hook=f'{GATE} > >(tee {G}/gate-run.log) 2>&1',
         exec='%%gate:4%% > >(tee gate-run.log) 2>&1',
         why="进程替换接 tee"),
    dict(id="C09", bg=True,
         hook="cd research && nice -n 19 bash scripts/mutate.sh e152_file_system_benchmark e7-index-bench/src/bin/e152_file_system_benchmark.rs mutations/e152_file_system_benchmark.tsv > /tmp/claude-1000/runner-x/mutate.log 2>&1; echo \"exit=$?\" >> /tmp/claude-1000/runner-x/mutate.log",
         exec='cd . && %%gate:4%% > mutate.log 2>&1; echo "exit=$?" >> mutate.log',
         why="长命令链（experiment-runner 跑变异表那种）"),
    dict(id="C10", bg=True,
         hook="{ nice -n 19 bash .claude/gate.d/54-crash-points.sh; echo \"exit=$?\"; } > /tmp/claude-1000/crash-x/54.log 2>&1",
         exec='{ %%gate:4%%; echo "exit=$?"; } > 54.log 2>&1',
         why="crash-verifier.md 第 24 行给的后台跑法原样"),
    dict(id="C11", bg=True,
         hook="{ nice -n 19 bash .claude/gate.d/54-crash-points.sh; echo \"exit=$?\"; } > /tmp/claude-1000/crash-x/54.log 2>&1 &",
         exec='{ %%gate:4%%; echo "exit=$?"; } > 54.log 2>&1 &',
         why="同上、末尾多一个 &"),
    dict(id="C12", bg=True,
         hook=f"for stage in 54 55 57; do nice -n 19 bash .claude/gate.d/$stage-*.sh > {G}/$stage.log 2>&1 & done; wait",
         exec="for stage in a b c; do bash %%DIR%%/work.sh $stage 4 > $stage.log 2>&1 & done; wait",
         why="for 循环里放后台、循环后 wait"),
    dict(id="C13", bg=True,
         hook=f'{KEEP} & {GATE} > {G}/gate-run.log 2>&1 & wait',
         exec='%%keepalive:2%% & %%gate:6%% > gate-run.log 2>&1 & wait',
         why="长活与计时器塞进同一条、并行加 wait（新指令「并行起几个再 wait 的照常写」字面允许）"),
]
